import SortableTable from "./SortableTable.jsx";
const STAGES=[
  ["paddle","Paddle OCR",[["page","Page"],["pass","Result"],["n_tokens","Tokens"],["n_lines","Lines"],["mean_confidence","Mean confidence"],["elapsed_s","Seconds"]]],
  ["geometry","Token Geometry",[["page","Page"],["pass","Result"],["n_bands","Bands"],["n_phrases","Phrases"],["n_marker_candidates","Markers"],["n_money_candidates","Money"],["n_recurring_columns","Columns"],["elapsed_s","Seconds"]]],
  ["sections","Sections",[["page","Page"],["pass","Result"],["n_header_sections","Headers"],["n_column_sections","Columns"],["n_main_text_boundaries","Main bounds"],["n_row_sections","Rows"],["n_cell_sections","Cells"],["n_nonempty_cell_sections","Nonempty"],["n_flags","Flags"],["elapsed_s","Seconds"]]],
  ["tree","By-OU Tree",[["page","Page"],["pass","Result"],["n_rows","Source rows"],["n_nodes","Nodes"],["n_review_flags","Review flags"],["n_flags","All flags"],["elapsed_s","Seconds"]]],
  ["pap","PAP Tree",[["page","Page"],["pass","Result"],["n_rows","Source rows"],["n_nodes","Nodes"],["n_review_flags","Review flags"],["n_flags","All flags"],["elapsed_s","Seconds"]]],
  ["totals","Tree Totals",[["page","Page"],["pass","Result"],["n_checks","Checks"],["n_comparable","Comparable"],["n_pass","Match"],["n_mismatch","Mismatch"],["n_review","Review"]]],
  ["run","Run",[["stage","Stage"],["pass","Result"],["exit_code","Exit"],["elapsed_s","Seconds"],["started_at","Started"]]],
];
export default function QaModal({open,onClose,qa,run,page,onPage,stage,setStage}){if(!open)return null;const config=STAGES.find((x)=>x[0]===stage)||STAGES[0],summary=qa[config[0]],rows=(config[0]==="run"?summary?.executions:summary?.pages)||[],status=summary?.pass===false||summary?.n_fail>0||summary?.n_reject>0?"fail":summary?.n_flags>0||summary?.n_review>0||summary?.n_weak>0?"review":"pass",columns=config[2];return <div className="qa-modal" onMouseDown={(e)=>e.target===e.currentTarget&&onClose()}><div className="qa-card"><div className="qa-header"><div><h2>Run QA</h2><span className="muted">{run}</span></div><button onClick={onClose}>×</button></div><nav className="qa-tabs">{STAGES.map(([id,title])=>{const value=qa[id],kind=value?.pass===false||value?.n_fail>0?"fail":value?.n_flags>0||value?.n_review>0||value?.n_weak>0?"review":"pass";return <button key={id} className={stage===id?"active":""} onClick={()=>setStage(id)}>{title}<span className={`qa-dot ${value?kind:"missing"}`}>{value?"✓":"—"}</span></button>})}</nav><div className="qa-content">{!summary?<p className="muted">No retained QA artifact for this stage.</p>:<><div className="metrics"><Metric label="Gate" value={summary.gate||summary.name}/><Metric label="Status" value={status.toUpperCase()} kind={status}/><Metric label="Pages" value={summary.n_pages}/><Metric label="Failures" value={summary.n_fail??0}/><Metric label="Flags" value={summary.n_flags??0}/><Metric label="Elapsed" value={`${summary.elapsed_s??"—"}s`}/></div><SortableTable headers={columns.map(([,label])=>label)} rows={rows} cells={(row)=>columns.map(([key])=>row[key])} rowKey={(row,index)=>row.page??row.stage??index} rowProps={(row)=>({className:row.page===page?"current-page":""})} renderCell={(value,column,row)=>{const key=columns[column][0];return key==="page"?<button className="link" onClick={()=>onPage(row.page)}>p.{row.page}</button>:key==="pass"?<strong className={row.pass===false?"fail":(row.n_flags??row.n_findings??0)>0||row.n_review>0||row.n_weak>0?"review":"pass"}>{row.pass===false?"FAIL":(row.n_flags??row.n_findings??0)>0||row.n_review>0||row.n_weak>0?"REVIEW":"PASS"}</strong>:format(value)}}/><details><summary>Raw retained JSON</summary><pre>{JSON.stringify(summary,null,2)}</pre></details></>}</div></div></div>}
function Metric({label,value,kind=""}){return <div className="metric"><span>{label}</span><strong className={kind}>{value??"—"}</strong></div>};const format=(value)=>Array.isArray(value)?value.join(", "):typeof value==="boolean"?(value?"Yes":"No"):value??"—";
