const STAGES=[
  ["paddle","Paddle OCR",[["page","Page"],["pass","Result"],["n_tokens","Tokens"],["n_lines","Lines"],["mean_confidence","Mean confidence"],["elapsed_s","Seconds"]]],
  ["geometry","Token Geometry",[["page","Page"],["pass","Result"],["n_bands","Bands"],["n_phrases","Phrases"],["n_marker_candidates","Markers"],["n_money_candidates","Money"],["n_recurring_columns","Columns"],["elapsed_s","Seconds"]]],
  ["extract","Extract",[["page","Page"],["pass","Result"],["n_tokens","Tokens"],["n_lines","Lines"],["n_zones","Zones"],["elapsed_s","Seconds"]]],
  ["schema","Schema",[["page","Page"],["pass","Result"],["schema_mode","Mode"],["confidence","Confidence"],["n_accept","Accept"],["n_review","Review"],["n_reject","Reject"],["carry_used","Carry"]]],
  ["run","Run",[["stage","Stage"],["pass","Result"],["exit_code","Exit"],["elapsed_s","Seconds"],["started_at","Started"]]],
];
export default function QaModal({open,onClose,qa,run,page,onPage,stage,setStage}){if(!open)return null;const config=STAGES.find((x)=>x[0]===stage)||STAGES.find((x)=>x[0]==="schema"),summary=qa[config[0]],rows=(config[0]==="run"?summary?.executions:summary?.pages)||[],status=summary?.pass===false||summary?.n_fail>0||summary?.n_reject>0?"fail":summary?.n_review>0||summary?.n_weak>0?"review":"pass";return <div className="qa-modal" onMouseDown={(e)=>e.target===e.currentTarget&&onClose()}><div className="qa-card"><div className="qa-header"><div><h2>Run QA</h2><span className="muted">{run}</span></div><button onClick={onClose}>×</button></div><nav className="qa-tabs">{STAGES.map(([id,title])=>{const value=qa[id],kind=value?.pass===false||value?.n_fail>0?"fail":value?.n_review>0||value?.n_weak>0?"review":"pass";return <button key={id} className={stage===id?"active":""} onClick={()=>setStage(id)}>{title}<span className={`qa-dot ${value?kind:"missing"}`}>{value?"✓":"—"}</span></button>})}</nav><div className="qa-content">{!summary?<p className="muted">No retained QA artifact for this stage.</p>:<><div className="metrics"><Metric label="Gate" value={summary.gate||summary.name}/><Metric label="Status" value={status.toUpperCase()} kind={status}/><Metric label="Pages" value={summary.n_pages}/><Metric label="Failures" value={summary.n_fail??0}/><Metric label="Reviews" value={summary.n_review??summary.n_weak??0}/><Metric label="Elapsed" value={`${summary.elapsed_s??"—"}s`}/></div><table><thead><tr>{config[2].map(([,label])=><th key={label}>{label}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i} className={row.page===page?"current-page":""}>{config[2].map(([key])=><td key={key}>{key==="page"?<button className="link" onClick={()=>onPage(row.page)}>p.{row.page}</button>:key==="pass"?<strong className={row.pass===false?"fail":row.n_review>0||row.n_weak>0?"review":"pass"}>{row.pass===false?"FAIL":row.n_review>0||row.n_weak>0?"REVIEW":"PASS"}</strong>:format(row[key])}</td>)}</tr>)}</tbody></table><details><summary>Raw retained JSON</summary><pre>{JSON.stringify(summary,null,2)}</pre></details></>}</div></div></div>}
function Metric({label,value,kind=""}){return <div className="metric"><span>{label}</span><strong className={kind}>{value??"—"}</strong></div>};const format=(value)=>Array.isArray(value)?value.join(", "):typeof value==="boolean"?(value?"Yes":"No"):value??"—";
